"""listing class

Revision ID: e9a0b1defcff
Revises: bf71766d43fa
Create Date: 2018-07-05 15:17:38.471268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a0b1defcff'
down_revision = 'bf71766d43fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('featured_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'featured_pic_path')
    # ### end Alembic commands ###
